alter table chains
alter column id
drop identity;

alter table chains
alter column id add generated by default as identity;

alter table slashing_events
alter column id
drop identity;

alter table slashing_events
alter column id add generated by default as identity;

alter table sync_statuses
alter column id
drop identity;

alter table sync_statuses
alter column id add generated by default as identity;
