const OMISSION = "...";
const MAX_MONIKER_LENGTH = 64;
const MAX_MONIKER_LENGTH_WITH_OMISSION = MAX_MONIKER_LENGTH - OMISSION.length;

export { OMISSION, MAX_MONIKER_LENGTH, MAX_MONIKER_LENGTH_WITH_OMISSION };
